/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DinePay } from "./DinePay";
export * as factories from "./factories";
export { DinePay__factory } from "./factories/DinePay__factory";
